### ISSUE TITLE
Installing requirements.txt fails, then fails on No such file or directory: '/var/www/Lychee/uploads/big'

### ISSUE THREAD

**Issue by NucleaPeon** [GustavePate/lycheesync#102]
```
Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-prdc1_lx/pillow_c3cbf08f56d049038e290dfa68203b7f/setup.py", line 733, in <module>
          setup(
        File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/tmp/pip-install-prdc1_lx/pillow_c3cbf08f56d049038e290dfa68203b7f/setup.py", line 513, in build_extensions
          raise ValueError(
      ValueError: --enable-jpeg requested but jpeg not found, aborting.
      [end of output]

```

Running this on Debian 12 and Lychee v4-13.0 with direnv handling the virtual environment. Unfortunately I don't have python 3.4 available since it's so old. I'm using python3.11 and since requirements.txt failed, I removed all version parameters and installed latest of everything instead.

Install completed so I created my configuration file and ran the command, only to get this traceback:

```
vagrant@bookworm:~/lycheesync$ python -m lycheesync.sync /images/ /var/www/Lychee/ lycheesync.conf 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/vagrant/lycheesync/lycheesync/sync.py", line 116, in <module>
    main()
  File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/lycheesync/lycheesync/sync.py", line 82, in main
    stat_info = os.stat(img_path)
                ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/Lychee/uploads/big'
```
There is no 'big' folder as far as I can tell:
```
vagrant@bookworm:~/lycheesync$ ls /var/www/Lychee/public/uploads/
import  medium  medium2x  original  small  small2x  thumb  thumb2x  tracks
```

but paths don't match either (Lychee/uploads/ vs /Lychee/public/uploads/).

**Comment by NucleaPeon** [comment]
Modified the sync.py script
```
diff --git a/lycheesync/sync.py b/lycheesync/sync.py
index 4b09e5d..a0fc25b 100644
--- a/lycheesync/sync.py
+++ b/lycheesync/sync.py
@@ -78,7 +78,7 @@ def main(verbose, exclusive_mode, sort_album_by_name, sanitycheck, link, updated
     #    conf_data["sort"] = True
 
     # read permission of the lycheepath directory to apply it to the uploade photos
-    img_path = os.path.join(conf_data["lycheepath"], "uploads", "big")
+    img_path = os.path.join(conf_data["lycheepath"], "public", "uploads", "original")
     stat_info = os.stat(img_path)
     uid = stat_info.st_uid
     gid = stat_info.st_gid
diff --git a/requirements.txt b/requirements.txt
index 3846504..64202fc 100644
```

But then I get this error:
```
vagrant@bookworm:~/lycheesync$ python -m lycheesync.sync /images/ /var/www/Lychee/ lycheesync.conf 
INFO;2023-10-16 18:45:56,385; __main__; =================== start adding to lychee ==================
ERROR;2023-10-16 18:45:56,391; lycheesync.lycheedao; (1146, "Table 'lychee_db.lychee_albums' doesn't exist")
ERROR;2023-10-16 18:45:56,392; __main__; Failed to run batch
Traceback (most recent call last):
  File "/home/vagrant/lycheesync/lycheesync/sync.py", line 105, in main
    s.sync()
  File "/home/vagrant/lycheesync/lycheesync/lycheesyncer.py", line 332, in sync
    self.dao = LycheeDAO(self.conf)
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/lycheesync/lycheesync/lycheedao.py", line 62, in __init__
    self.loadAlbumList()
  File "/home/vagrant/lycheesync/lycheesync/lycheedao.py", line 209, in loadAlbumList
    cur.execute("SELECT title,id from lychee_albums")
  File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/pymysql/cursors.py", line 146, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/pymysql/cursors.py", line 296, in _query
    conn.query(q)
  File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/pymysql/connections.py", line 819, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/pymysql/connections.py", line 1001, in _read_query_result
    result.read()
  File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/pymysql/connections.py", line 1285, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/pymysql/connections.py", line 965, in _read_packet
    packet.check_error()
  File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/pymysql/connections.py", line 394, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/home/vagrant/lycheesync/.direnv/python-3.11/lib/python3.11/site-packages/pymysql/err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
pymysql.err.ProgrammingError: (1146, "Table 'lychee_db.lychee_albums' doesn't exist")
ERROR;2023-10-16 18:45:56,395; __main__; =================== script ended with errors ==================
```

`lychee_albums` should be `base_albums` and `lychee_photos` should be `photos`. Probably a good idea to put table names in their own variable and use python string formatting to interpolate them.

**Comment by d7415** [comment]
> Running this on Debian 12 and Lychee v4-13.0

This project only supports Lychee v3. Take a look at [this](https://lycheeorg.github.io/docs/faq_general.html#can-i-set-up-lychee-to-watch-a-folder-for-new-images-and-automatically-add-them-to-albums) or [this](https://github.com/LycheeOrg/Lychee/blob/master/app/Console/Commands/Sync.php) instead for v4.

**Comment by NucleaPeon** [comment]
Thanks for responding. I actually just saw someone post about using the `:sync` command and I'm doing that now, so that solves my issue. Thanks!
