### ISSUE TITLE
long folder/directory names

### ISSUE THREAD

**Issue by denisl-27** [GustavePate/lycheesync#26]
Hi Gustave,
Looks like lycheesync is failing on creating albums where the directory names on the source are very long.  Maybe a character limit in mysql? Of the few thousand photos I tried to import only 2 albums failed to create.  I think it's something you can probably easily recreate by adding a directory and subdirectory with a very long name.  

I'm trying to figure out how to increase the column character limit.  I'll give it a shot and report back. Here's the lychee_albums column details from mysql and title is 50 characters:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

mysql> show columns from lychee_albums from lychee;

+--------------+---------------+------+-----+---------+----------------+
| Field        | Type          | Null | Key | Default | Extra          |
+--------------+---------------+------+-----+---------+----------------+
| id           | int(11)       | NO   | PRI | NULL    | auto_increment |
| title        | varchar(50)   | NO   |     | NULL    |                |
| description  | varchar(1000) | YES  |     |         |                |
| sysstamp     | int(11)       | NO   |     | NULL    |                |
| public       | tinyint(1)    | NO   |     | 0       |                |
| visible      | tinyint(1)    | NO   |     | 1       |                |
| downloadable | tinyint(1)    | NO   |     | 0       |                |
| password     | varchar(100)  | YES  |     | NULL    |                |
+--------------+---------------+------+-----+---------+----------------+

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Here's the log from my latest sync:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

root@p-vubulychee01:/home/lycheesync/lycheesync-master# python main.py /export/nas/owncloud/data/Victoria/files/Pictures/ /var/www/html/Lychee/ /home/lycheesync/lyche                    esync-master/conf.json
/home/lycheesync/lycheesync-master/lycheedao.py:179: Warning: Data truncated for column 'title' at row 1
  cur.execute(query, data)
ERROR createAlbum:sesame place denis, linda and kids october 2nd 2011 -> {'path': '/export/nas/owncloud/data/Victoria/files/Pictures/Sesame place Denis, Linda and kids October 2nd 2011', 'relpath': 'Sesame place Denis, Linda and kids October 2nd 2011', 'id': None, 'photos': [], 'name': 'sesame place denis, linda and kids october 2nd 2011'}
ERROR while executing: select id from lychee_albums where title='sesame place denis, linda and kids october 2nd 2011'
Traceback (most recent call last):
  File "/home/lycheesync/lycheesync-master/lycheedao.py", line 185, in createAlbum
    self.albumslist['name'] = row[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
ERROR didn't manage to create album for: Sesame place Denis, Linda and kids October 2nd 2011
/home/lycheesync/lycheesync-master/lycheedao.py:279: Warning: Data truncated for column 'title' at row 1
  res = cur.execute(query, data)
ERROR createAlbum:victoria's birthdays_victoria's birthday  2013 at manalapan house -> {'path': "/export/nas/owncloud/data/Victoria/files/Pictures/Victoria's birthdays/Victoria's birthday  2013 at Manalapan house", 'relpath': "Victoria's birthdays/Victoria's birthday  2013 at Manalapan house", 'id': None, 'photos': [], 'name': "victoria's birthdays_victoria's birthday  2013 at manalapan house"}
ERROR while executing: select id from lychee_albums where title='victoria\'s birthdays_victoria\'s birthday  2013 at manalapan house'
Traceback (most recent call last):
  File "/home/lycheesync/lycheesync-master/lycheedao.py", line 185, in createAlbum
    self.albumslist['name'] = row[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
ERROR didn't manage to create album for: Victoria's birthdays/Victoria's birthday  2013 at Manalapan house

Directory scanned: /export/nas/owncloud/data/Victoria/files/Pictures/
Created albums:  39
3050 photos imported on 3050 discovered
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by GustavePate** [comment]
Hi denis,

Lychee's database is the proprety of the lychee project  not lycheesync.
I use their database schema but I won't modify it.

However, I should protect the code in order not to display error but only a warning and provide properly truncated album name.

I advise you to adjust your directory names rather than tweak lychee's db (which can change whenever project lychee  wants to)

TODO: truncate album names if needed

**Comment by denisl-27** [comment]
Thanks Gustave
very good point on modifying the Lychee DB.  However, for my personal purposes I think I prefer the "user level" workaround of increasing the character length.  If you update your program to truncate, can you first add logic that will only truncate if an error is encountered? If you automatically truncate any album > 50 characters than my user level workaround by increasing the characters of the title will no longer work.  I made the change on my end and it works great.  

I had one error below but have not yet figured out what caused it.  The Lychee albums all look great.

~~~~~~~~~~~~~~~~~~~~
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| lychee             |
+--------------------+
2 rows in set (0.00 sec)

mysql> connect lychee
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Connection id:    42
Current database: lychee

mysql> show columns from lychee_albums from lychee;
+--------------+---------------+------+-----+---------+----------------+
| Field        | Type          | Null | Key | Default | Extra          |
+--------------+---------------+------+-----+---------+----------------+
| id           | int(11)       | NO   | PRI | NULL    | auto_increment |
| title        | varchar(50)   | NO   |     | NULL    |                |
| description  | varchar(1000) | YES  |     |         |                |
| sysstamp     | int(11)       | NO   |     | NULL    |                |
| public       | tinyint(1)    | NO   |     | 0       |                |
| visible      | tinyint(1)    | NO   |     | 1       |                |
| downloadable | tinyint(1)    | NO   |     | 0       |                |
| password     | varchar(100)  | YES  |     | NULL    |                |
+--------------+---------------+------+-----+---------+----------------+
8 rows in set (0.01 sec)

mysql> ALTER TABLE lychee_albums MODIFY title VARCHAR(100);
Query OK, 0 rows affected (0.01 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> show columns from lychee_albums from lychee;
+--------------+---------------+------+-----+---------+----------------+
| Field        | Type          | Null | Key | Default | Extra          |
+--------------+---------------+------+-----+---------+----------------+
| id           | int(11)       | NO   | PRI | NULL    | auto_increment |
| title        | varchar(100)  | YES  |     | NULL    |                |
| description  | varchar(1000) | YES  |     |         |                |
| sysstamp     | int(11)       | NO   |     | NULL    |                |
| public       | tinyint(1)    | NO   |     | 0       |                |
| visible      | tinyint(1)    | NO   |     | 1       |                |
| downloadable | tinyint(1)    | NO   |     | 0       |                |
| password     | varchar(100)  | YES  |     | NULL    |                |
+--------------+---------------+------+-----+---------+----------------+
8 rows in set (0.00 sec)

mysql> quit
Bye
root@p-vubulychee01:/var/www/html/Lychee# cd /home/lycheesync/lycheesync-master
root@p-vubulychee01:/home/lycheesync/lycheesync-master# python main.py /export/nas/owncloud/data/Victoria/files/Pictures/ /var/www/html/Lychee/ /home/lycheesync/lycheesync-master/conf.js    on
/home/lycheesync/lycheesync-master/lycheedao.py:279: Warning: Data truncated for column 'title' at row 1
  res = cur.execute(query, data)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Directory scanned: /export/nas/owncloud/data/Victoria/files/Pictures/
Created albums:  41
3179 photos imported on 3179 discovered
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
root@p-vubulychee01:/home/lycheesync/lycheesync-master#
~~~~~~~~~~~~~~~~~~~~~~

**Comment by GustavePate** [comment]
My modification reads the colum width in the DB and truncate the album's name accordingly.
No problem for you.

You don't have the latest lycheesync version (not commited yet) so code line number vary with my local repo. But I think that the warning you encounter is also a width problem but this time on the photo description or name.
