### ISSUE TITLE
Invalid Taketime / 'int' object has no attribute '_getitem_'

### ISSUE THREAD

**Issue by RoedeanMC** [GustavePate/lycheesync#62]
Good Afternoon,

I have just setup Lychee and LycheeSync for the first time on an Ubuntu server. The website it self seems to be working perfectly I can upload photos and its all happy however I am having a problem with lycheesync in the fact its creating albumbs but it won't uplaod the images:

INFO;2016-05-12 11:47:50,672; __main__; =================== start adding to lychee ==================
ERROR;2016-05-12 11:47:50,674; lycheesync.lycheedao; host: localhost
ERROR;2016-05-12 11:47:50,674; lycheesync.lycheedao; user: lychee
ERROR;2016-05-12 11:47:50,675; lycheesync.lycheedao; password: images
ERROR;2016-05-12 11:47:50,675; lycheesync.lycheedao; db: lychee
ERROR;2016-05-12 11:47:50,675; lycheesync.lycheedao; unix_socket: /var/run/mysqld/mysqld.sock
WARNING;2016-05-12 11:47:50,759; lycheesync.lycheemodel; invalid taketime: 2015:02:15 09:43:47 for /images/images/Trips/Physics Iceland 2015 004.JPG
ERROR;2016-05-12 11:47:50,760; lycheesync.lycheesyncer; 'int' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "lycheesync/lycheesyncer.py", line 419, in sync
    photo = LycheePhoto(self.conf, f, album)
  File "lycheesync/lycheemodel.py", line 225, in __init__
    self.exif.iso = value[0]
TypeError: 'int' object has no attribute '__getitem__'
ERROR;2016-05-12 11:47:50,760; lycheesync.lycheesyncer; could not add Physics Iceland 2015 004.JPG to album Trips
INFO;2016-05-12 11:47:50,762; lycheesync.lycheesyncer; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO;2016-05-12 11:47:50,762; lycheesync.lycheesyncer; Directory scanned:/images/images
INFO;2016-05-12 11:47:50,762; lycheesync.lycheesyncer; Created albums: 0
ERROR;2016-05-12 11:47:50,762; lycheesync.lycheesyncer; 0 photos imported on 1 discovered
INFO;2016-05-12 11:47:50,763; lycheesync.lycheesyncer; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO;2016-05-12 11:47:50,763; __main__; =================== script successfully ended ==================

However if I open up Paint.Net make a lovely drawing and save it then lycheesync uploads it to Lychee absolutly fine so I know it is actually working so whats the problems with our photos?

**Comment by palitu** [comment]
try running the script as sudo - i found it tended to fix permission issues.

**Comment by RoedeanMC** [comment]
Afraid not I have tried:
sudo python -m lycheesync.sync /images/images /images/www /images/lycheesync/ressources/conf.json

Its sucessfully adding tons of photos but it still fails on alot:

DEBUG;2016-05-13 09:37:35,835; lycheesync.lycheesyncer; **** Trying to add to lychee album Departments_Academic Departments_Modern Foreign Languages_German_German Students 07_06_Roedean Girls: /images/images/Departments/Academic Departments/Modern Foreign Languages/German/German Students 07/06/Roedean Girls in Germany/Andrea.JPG
WARNING;2016-05-13 09:37:35,865; lycheesync.lycheemodel; invalid taketime: 2006:11:24 11:21:48 for /images/images/Departments/Academic Departments/Modern Foreign Languages/German/German Students 07/06/Roedean Girls in Germany/Andrea.JPG
DEBUG;2016-05-13 09:37:35,866; lycheesync.lycheemodel; aperture only a few digit after comma: 4.67680523946e+49
DEBUG;2016-05-13 09:37:35,867; lycheesync.lycheemodel; quantize result has too many digits for current context
ERROR;2016-05-13 09:37:35,867; lycheesync.lycheesyncer; 'int' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "lycheesync/lycheesyncer.py", line 419, in sync
    photo = LycheePhoto(self.conf, f, album)
  File "lycheesync/lycheemodel.py", line 225, in __init__
    self.exif.iso = value[0]
TypeError: 'int' object has no attribute '__getitem__'
ERROR;2016-05-13 09:37:35,868; lycheesync.lycheesyncer; could not add Andrea.JPG to album Departments_Academic Departments_Modern Foreign Languages_German_German Students 07_06_Roedean Girls


The other problem I am having is all the photos on the lychee web server have todays date even though there is exif data on the photo files which I presume is because of this:

DEBUG;2016-05-13 09:42:41,199; lycheesync.lycheesyncer; **** Trying to add to lychee album Departments_Academic Departments_Modern Foreign Languages_German_German Students 07_07_Roedean in Du: /images/images/Departments/Academic Departments/Modern Foreign Languages/German/German Students 07/07/Roedean in Duisburg 2 2007/IMGP0677.JPG
WARNING;2016-05-13 09:42:41,239; lycheesync.lycheemodel; invalid taketime: 2007:12:10 14:26:11 for /images/images/Departments/Academic Departments/Modern Foreign Languages/German/German Students 07/07/Roedean in Duisburg 2 2007/IMGP0677.JPG
DEBUG;2016-05-13 09:42:41,720; lycheesync.lycheedao; insert into lychee_photos (id, url, public, type, width, height, size, star, thumbUrl, album,iso, aperture, make, model, shutter, focal, takestamp, description, title, checksum) values (14631289616781, '049ae54d9b52f8776d76b9245878573e.jpg', 1, 'image/jpeg', 2048.0, 1536.0, '1665 KB', 0, '049ae54d9b52f8776d76b9245878573e.jpg', '310', '', 'F32768.1', 'PENTAX Corporation', 'PENTAX Optio 33WR', '10.00 s', '57 mm', '1462195571', '2 14:26:11', %s, '5e5dbc436083883af56fd97cd3e3ca8bcb65e701')
INFO;2016-05-13 09:42:41,722; lycheesync.lycheesyncer; **** Successfully added /images/images/Departments/Academic Departments/Modern Foreign Languages/German/German Students 07/07/Roedean in Duisburg 2 2007/IMGP0677.JPG to lychee album Departments_Academic Departments_Modern Foreign Languages_German_German Students 07_07_Roedean in Du

**Comment by RoedeanMC** [comment]
Any suggestions I am a little stuck on this one...

**Comment by GustavePate** [comment]
Hi !

First thanks for this bug report.

OK, as far as I can see, your image has an exotic exif storage for the iso value.
It crashes so every other exif information are lost (and there is your date problem).

in File "lycheesync/lycheemodel.py", line 225, in init
change

`self.exif.iso = value[0]`

with

`self.exif.iso = value`

This will fix the problem for the photos taken with this camera but is likely to crash other photos.
Give it a try if you want.

To definitely fix your problem, is it possible for you to send me a picture that cause this bug so that I can reproduce your bug and fix it without breaking lycheesync and use it to my test suite ?

Thanks again

**Comment by vijamaica** [comment]
Hello GustavePate, I'm also facing this issue.
Here you ara a photo sample to try helping your investigation.

Thanks for all your contribution
![img_8006](https://cloud.githubusercontent.com/assets/22646376/19130042/004cfd2c-8b20-11e6-8045-ba1d2ecbfa18.JPG)

**Comment by rwbrady** [comment]
Hello, 

I am also getting this error on certain images upon import. oddly enough, some pictures taken with the same phone work and others throw the error.

`Traceback (most recent call last):
  File "/var/www/photo-import/lycheesync/lycheesync/lycheesyncer.py", line 426, in sync
    photo = LycheePhoto(pid, self.conf, f, album)
  File "/var/www/photo-import/lycheesync/lycheesync/lycheemodel.py", line 214, in __init__
    self.exif.iso = value[0]
TypeError: 'int' object is not subscriptable
`

if i modify self.exif.iso as described above it then throws

`Traceback (most recent call last):
  File "/var/www/photo-import/lycheesync/lycheesync/lycheesyncer.py", line 426, in sync
    photo = LycheePhoto(pid, self.conf, f, album)
  File "/var/www/photo-import/lycheesync/lycheesync/lycheemodel.py", line 222, in __init__
    s = decimal.Decimal(s).quantize(decimal.Decimal('1'), rounding=decimal.ROUND_05UP)
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
`
if i modify the value of 's' in shutterspeed the same way (array0->string) it then throws

`Traceback (most recent call last):
  File "/var/www/photo-import/lycheesync/lycheesync/lycheesyncer.py", line 426, in sync
    photo = LycheePhoto(pid, self.conf, f, album)
  File "/var/www/photo-import/lycheesync/lycheesync/lycheemodel.py", line 221, in __init__
    s = 2 ** s
TypeError: unsupported operand type(s) for ** or pow(): 'int' and 'tuple'
`

i'm very unfamiliar with python so any help would be greatly appreciated, thanks!
