### ISSUE TITLE
quantize result has too many digits for current context

### ISSUE THREAD

**Issue by beardyjesse** [GustavePate/lycheesync#73]
Hi,

I love the idea of your sync script as this is exactly how I'd envisioned using lychee when I first saw it.  However having set up the sync programme, I'm having trouble importing photos - I'm receiving the following error;

`DEBUG;2016-09-26 23:20:26,313; lycheesync.lycheesyncer; **** Trying to add to lychee album S90: /home/beard/data/backup/Pictures/2010/12/S90/IMG_2024.JPG
WARNING;2016-09-26 23:20:26,326; lycheesync.lycheemodel; invalid taketime: 2010:12:31 04:08:53 for /home/beard/data/backup/Pictures/2010/12/S90/IMG_2024.JPG
ERROR;2016-09-26 23:20:26,327; lycheesync.lycheesyncer; quantize result has too many digits for current context
Traceback (most recent call last):
  File "lycheesync/lycheesyncer.py", line 426, in sync
    photo = LycheePhoto(pid, self.conf, f, album)
  File "lycheesync/lycheemodel.py", line 222, in __init__
    s = decimal.Decimal(s).quantize(decimal.Decimal('1'), rounding=decimal.ROUND_05UP)
  File "/usr/lib/python2.7/decimal.py", line 2469, in quantize
    'quantize result has too many digits for current context')
  File "/usr/lib/python2.7/decimal.py", line 3873, in _raise_error
    raise error(explanation)
InvalidOperation: quantize result has too many digits for current context
ERROR;2016-09-26 23:20:26,327; lycheesync.lycheesyncer; could not add IMG_2024.JPG to album S90
`

Please find the example image attached.  Any ideas/tweaks that could eliminate this?

![img_2024](https://cloud.githubusercontent.com/assets/22459872/18854319/70cc0e4c-8442-11e6-94ad-bc2123b53655.JPG)

**Comment by titibandit** [comment]
I'm affected by the exact same issue. I think it's dependent on the pictures. I have a Canon 5D Mark 1 and I export my pictures using darktable.

**Comment by titibandit** [comment]
Okay I seemed to have solved it by using the 3.1 branch of lycheesync. Maybe this should get merged to the master branch?
