### ISSUE TITLE
Sync fails with "TypeError: 'int' object has no attribute '__getitem__'"

### ISSUE THREAD

**Issue by jacotec** [GustavePate/lycheesync#80]
Hi,

I've discovered Lychee which looks like a good management tool for all the photos we sync automatically from our iPhones to a local Seafile server.

Unfortunately the very most photos do not sync due to an error. Affected are photos which are real photos taken by the iPhone camera while screenshots do sync.

```
ERROR;2017-12-30 21:02:09,348; lycheesync.lycheesyncer; could not add IMG_2497.JPG to album Marcos-IPhone-8Plus_2017
WARNING;2017-12-30 21:02:10,172; lycheesync.lycheemodel; invalid taketime: 2017:02:17 15:33:13 for /mnt/marco/IPhone/Marcos-IPhone-8Plus/2017/IMG_2498.JPG
ERROR;2017-12-30 21:02:10,172; lycheesync.lycheesyncer; 'int' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "lycheesync/lycheesyncer.py", line 426, in sync
    photo = LycheePhoto(pid, self.conf, f, album)
  File "lycheesync/lycheemodel.py", line 214, in __init__
    self.exif.iso = value[0]
TypeError: 'int' object has no attribute '__getitem__'
```

**Comment by GustavePate** [comment]
Hi jacotec,

Sorry for the lag I have been very busy in the last month...
Could you provide me a photo that cause the problem ?

In theory it should be fixed in next release but I have currently no mean to test it and so to guarantee the fix is working.

**Comment by jacotec** [comment]
Hi Gustave,

sorry, I'm not using Lychee anymore. It was a trial, I've found what I was looking for with Picapport. 

mit freundlichen Grüßen / with best regards
Marco Jakobs

--
Zum Dickbusch 50
50171 Kerpen (Manheim-neu)
Tel: +49 2275 918875-0

Sent by my iPad

**Comment by donremo** [comment]
Hi Gustave,
is this next release already avialable? I am facing the same issue as Gustave:

> WARNING;2018-05-28 06:13:53,317; lycheesync.lycheesyncer; file at srcdir root won't be added to lychee, please move them in a subfolder: /media/hdd/LycheeImport
WARNING;2018-05-28 06:13:53,745; lycheesync.lycheemodel; invalid taketime: 2016:04:28 20:22:38 for /media/hdd/LycheeImport/201604 Maks !/IMG_0002.JPG
ERROR;2018-05-28 06:13:53,746; lycheesync.lycheesyncer; 'int' object has no attribute '_\_getitem__'
Traceback (most recent call last):
  File "lycheesync/lycheesyncer.py", line 426, in sync
    photo = LycheePhoto(pid, self.conf, f, album)
  File "lycheesync/lycheemodel.py", line 214, in \_\_init__
    self.exif.iso = value[0]
