### ISSUE TITLE
Script execution error - pymsql

### ISSUE THREAD

**Issue by Meiglus** [GustavePate/lycheesync#84]
Hi everyone,

since the original issue is closed, I open a new one, because I couldn't find a solution and cannot reopen it.. 
It's this one: https://github.com/GustavePate/lycheesync/issues/71

I feel free to quote myself:

---

Hi, 

I'd like to reopen this issue, because I have the same problem like c0d1ng. But I couldn't solve it by going through the installation again.. All tools are installed the debian way. 

I installed the packages like it says in the description:

> sudo apt-get install python3-dev python3 python3-pymysql python3-click python3-pil python3-dateutil libjpeg-dev

But still..

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/var/www/clients/client1/web31/web/lycheesync/lycheesync/sync.py", line 6, in <module>
>     from lycheesync.lycheesyncer import LycheeSyncer
>   File "lycheesync/lycheesyncer.py", line 8, in <module>
>     from lycheesync.lycheedao import LycheeDAO
>   File "lycheesync/lycheedao.py", line 5, in <module>
>     import pymysql
> ImportError: No module named pymysql

If I execute the command with python3 instead of python, I get:

> Traceback (most recent call last):
>   File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/var/www/clients/client1/web31/web/lycheesync/lycheesync/sync.py", line 6, in <module>
>     from lycheesync.lycheesyncer import LycheeSyncer
>   File "/var/www/clients/client1/web31/web/lycheesync/lycheesync/lycheesyncer.py", line 16, in <module>
>     import piexif
> ImportError: No module named 'piexif'

Any help here? :(

**Comment by VictorLamoine** [comment]
`pip3 install piexif`solves the problem.
Or `pip3 install -r requirements.txt` to install all the dependencies using pip
